CREATE TABLE countries (
country_code varchar(2) NOT NULL default '',
country_en_name varchar(100) NOT NULL default '',
country_ar_name nvarchar(100) NOT NULL default '',
country_en_nationality varchar(100) NOT NULL default '',
country_ar_nationality nvarchar(100) NOT NULL default '',
PRIMARY KEY (country_code)
)
-- 
-- Dumping data for table countries
-- 

INSERT INTO countries VALUES ('AF', N'Afghanistan',N'أفغانستان','Afghan',N'أفغانستاني');
INSERT INTO countries VALUES ('AL', 'Albania',N'ألبانيا','Albanian',N'ألباني');
INSERT INTO countries VALUES ('AX', 'Aland Islands',N'جزر آلاند','Aland Islander',N'آلاندي');
INSERT INTO countries VALUES ('DZ', 'Algeria',N'الجزائر','Algerian',N'جزائري');
INSERT INTO countries VALUES ('AS', 'American Samoa',N'ساموا-الأمريكي','American Samoan',N'أمريكي سامواني');
INSERT INTO countries VALUES ('AD', 'Andorra',N'أندورا','Andorran',N'أندوري');
INSERT INTO countries VALUES ('AO', 'Angola',N'أنغولا','Angolan',N'أنقولي');
INSERT INTO countries VALUES ('AI', 'Anguilla',N'أنغويلا','Anguillan',N'أنغويلي');
INSERT INTO countries VALUES ('AQ', 'Antarctica',N'أنتاركتيكا','Antarctican',N'أنتاركتيكي');
INSERT INTO countries VALUES ('AG', 'Antigua and Barbuda',N'أنتيغوا وبربودا','Antiguan',N'بربودي');
INSERT INTO countries VALUES ('AR', 'Argentina',N'الأرجنتين','Argentinian',N'أرجنتيني');
INSERT INTO countries VALUES ('AM', 'Armenia',N'أرمينيا','Armenian',N'أرميني');
INSERT INTO countries VALUES ('AW', 'Aruba',N'أروبه','Aruban',N'أوروبهيني');
INSERT INTO countries VALUES ('AU', 'Australia',N'أستراليا','Australian',N'أسترالي');
INSERT INTO countries VALUES ('AT', 'Austria',N'النمسا','Austrian',N'نمساوي');
INSERT INTO countries VALUES ('AZ', 'Azerbaijan',N'أذربيجان','Azerbaijani',N'أذربيجاني');
INSERT INTO countries VALUES ('BS', 'Bahamas',N'الباهاماس','Bahamian',N'باهاميسي');
INSERT INTO countries VALUES ('BH', 'Bahrain',N'البحرين','Bahraini',N'بحريني');
INSERT INTO countries VALUES ('BD', 'Bangladesh',N'بنغلاديش','Bangladeshi',N'بنغلاديشي');
INSERT INTO countries VALUES ('BB', 'Barbados',N'بربادوس','Barbadian',N'بربادوسي');
INSERT INTO countries VALUES ('BY', 'Belarus',N'روسيا البيضاء','Belarusian',N'روسي');
INSERT INTO countries VALUES ('BE', 'Belgium',N'بلجيكا','Belgian',N'بلجيكي');
INSERT INTO countries VALUES ('BZ', 'Belize',N'بيليز','Belizean',N'بيليزي');
INSERT INTO countries VALUES ('BJ', 'Benin',N'بنين','Beninese',N'بنيني');
INSERT INTO countries VALUES ('BL', 'Saint Barthelemy',N'سان بارتيلمي','Saint Barthelmian',N'سان بارتيلمي');
INSERT INTO countries VALUES ('BM', 'Bermuda',N'جزر برمودا','Bermudan',N'برمودي');
INSERT INTO countries VALUES ('BT', 'Bhutan',N'بوتان','Bhutanese',N'بوتاني');
INSERT INTO countries VALUES ('BO', 'Bolivia',N'بوليفيا','Bolivian',N'بوليفي');
INSERT INTO countries VALUES ('BA', 'Bosnia and Herzegovina',N'البوسنة و الهرسك','Bosnian / Herzegovinian',N'بوسني/هرسكي');
INSERT INTO countries VALUES ('BW', 'Botswana',N'بوتسوانا','Botswanan',N'بوتسواني');
INSERT INTO countries VALUES ('BV', 'Bouvet Island',N'جزيرة بوفيه','Bouvetian',N'بوفيهي');
INSERT INTO countries VALUES ('BR', 'Brazil',N'البرازيل','Brazilian',N'برازيلي');
INSERT INTO countries VALUES ('IO', 'British Indian Ocean Territory',N'إقليم المحيط الهندي البريطاني','British Indian Ocean Territory',N'إقليم المحيط الهندي البريطاني');
INSERT INTO countries VALUES ('BN', 'Brunei Darussalam',N'بروني','Bruneian',N'بروني');
INSERT INTO countries VALUES ('BG', 'Bulgaria',N'بلغاريا','Bulgarian',N'بلغاري');
INSERT INTO countries VALUES ('BF', 'Burkina Faso',N'بوركينا فاسو','Burkinabe',N'بوركيني');
INSERT INTO countries VALUES ('BI', 'Burundi',N'بوروندي','Burundian',N'بورونيدي');
INSERT INTO countries VALUES ('KH', 'Cambodia',N'كمبوديا','Cambodian',N'كمبودي');
INSERT INTO countries VALUES ('CM', 'Cameroon',N'كاميرون','Cameroonian',N'كاميروني');
INSERT INTO countries VALUES ('CA', 'Canada',N'كندا','Canadian',N'كندي');
INSERT INTO countries VALUES ('CV', 'Cape Verde',N'الرأس الأخضر','Cape Verdean',N'الرأس الأخضر');
INSERT INTO countries VALUES ('KY', 'Cayman Islands',N'جزر كايمان','Caymanian',N'كايماني');
INSERT INTO countries VALUES ('CF', 'Central African Republic',N'جمهورية أفريقيا الوسطى','Central African',N'أفريقي');
INSERT INTO countries VALUES ('TD', 'Chad',N'تشاد','Chadian',N'تشادي');
INSERT INTO countries VALUES ('CL', 'Chile',N'شيلي','Chilean',N'شيلي');
INSERT INTO countries VALUES ('CN', 'China',N'الصين','Chinese',N'صيني');
INSERT INTO countries VALUES ('CX', 'Christmas Island',N'جزيرة عيد الميلاد','Christmas Islander',N'جزيرة عيد الميلاد');
INSERT INTO countries VALUES ('CC', 'Cocos (Keeling) Islands',N'جزر كوكوس','Cocos Islander',N'جزر كوكوس');
INSERT INTO countries VALUES ('CO', 'Colombia',N'كولومبيا','Colombian',N'كولومبي');
INSERT INTO countries VALUES ('KM', 'Comoros',N'جزر القمر','Comorian',N'جزر القمر');
INSERT INTO countries VALUES ('CG', 'Congo',N'الكونغو','Congolese',N'كونغي');
INSERT INTO countries VALUES ('CK', 'Cook Islands',N'جزر كوك','Cook Islander',N'جزر كوك');
INSERT INTO countries VALUES ('CR', 'Costa Rica',N'كوستاريكا','Costa Rican',N'كوستاريكي');
INSERT INTO countries VALUES ('HR', 'Croatia',N'كرواتيا','Croatian',N'كوراتي');
INSERT INTO countries VALUES ('CU', 'Cuba',N'كوبا','Cuban',N'كوبي');
INSERT INTO countries VALUES ('CY', 'Cyprus',N'قبرص','Cypriot',N'قبرصي');
INSERT INTO countries VALUES ('CW', 'Curaçao',N'كوراساو','Curacian',N'كوراساوي');
INSERT INTO countries VALUES ('CZ', 'Czech Republic',N'الجمهورية التشيكية','Czech',N'تشيكي');
INSERT INTO countries VALUES ('DK', 'Denmark',N'الدانمارك','Danish',N'دنماركي');
INSERT INTO countries VALUES ('DJ', 'Djibouti',N'جيبوتي','Djiboutian',N'جيبوتي');
INSERT INTO countries VALUES ('DM', 'Dominica',N'دومينيكا','Dominican',N'دومينيكي');
INSERT INTO countries VALUES ('DO', 'Dominican Republic',N'الجمهورية الدومينيكية','Dominican',N'دومينيكي');
INSERT INTO countries VALUES ('EC', 'Ecuador',N'إكوادور','Ecuadorian',N'إكوادوري');
INSERT INTO countries VALUES ('EG', 'Egypt',N'مصر','Egyptian',N'مصري');
INSERT INTO countries VALUES ('SV', 'El Salvador',N'إلسلفادور','Salvadoran',N'سلفادوري');
INSERT INTO countries VALUES ('GQ', 'Equatorial Guinea',N'غينيا الاستوائي','Equatorial Guinean',N'غيني');
INSERT INTO countries VALUES ('ER', 'Eritrea',N'إريتريا','Eritrean',N'إريتيري');
INSERT INTO countries VALUES ('EE', 'Estonia',N'استونيا','Estonian',N'استوني');
INSERT INTO countries VALUES ('ET', 'Ethiopia',N'أثيوبيا','Ethiopian',N'أثيوبي');
INSERT INTO countries VALUES ('FK', 'Falkland Islands (Malvinas)',N'جزر فوكلاند','Falkland Islander',N'فوكلاندي');
INSERT INTO countries VALUES ('FO', 'Faroe Islands',N'جزر فارو','Faroese',N'جزر فارو');
INSERT INTO countries VALUES ('FJ', 'Fiji',N'فيجي','Fijian',N'فيجي');
INSERT INTO countries VALUES ('FI', 'Finland',N'فنلندا','Finnish',N'فنلندي');
INSERT INTO countries VALUES ('FR', 'France',N'فرنسا','French',N'فرنسي');
INSERT INTO countries VALUES ('GF', 'French Guiana',N'غويانا الفرنسية','French Guianese',N'غويانا الفرنسية');
INSERT INTO countries VALUES ('PF', 'French Polynesia',N'بولينيزيا الفرنسية','French Polynesian',N'بولينيزيي');
INSERT INTO countries VALUES ('TF', 'French Southern and Antarctic Lands',N'أراض فرنسية جنوبية وأنتارتيكية','French',N'أراض فرنسية جنوبية وأنتارتيكية');
INSERT INTO countries VALUES ('GA', 'Gabon',N'الغابون','Gabonese',N'غابوني');
INSERT INTO countries VALUES ('GM', 'Gambia',N'غامبيا','Gambian',N'غامبي');
INSERT INTO countries VALUES ('GE', 'Georgia',N'جيورجيا','Georgian',N'جيورجي');
INSERT INTO countries VALUES ('DE', 'Germany',N'ألمانيا','German',N'ألماني');
INSERT INTO countries VALUES ('GH', 'Ghana',N'غانا','Ghanaian',N'غاني');
INSERT INTO countries VALUES ('GI', 'Gibraltar',N'جبل طارق','Gibraltar',N'جبل طارق');
INSERT INTO countries VALUES ('GG', 'Guernsey',N'غيرنزي','Guernsian',N'غيرنزي');
INSERT INTO countries VALUES ('GR', 'Greece',N'اليونان','Greek',N'يوناني');
INSERT INTO countries VALUES ('GL', 'Greenland',N'جرينلاند','Greenlandic',N'جرينلاندي');
INSERT INTO countries VALUES ('GD', 'Grenada',N'غرينادا','Grenadian',N'غرينادي');
INSERT INTO countries VALUES ('GP', 'Guadeloupe',N'جزر جوادلوب','Guadeloupe',N'جزر جوادلوب');
INSERT INTO countries VALUES ('GU', 'Guam',N'جوام','Guamanian',N'جوامي');
INSERT INTO countries VALUES ('GT', 'Guatemala',N'غواتيمال','Guatemalan',N'غواتيمالي');
INSERT INTO countries VALUES ('GN', 'Guinea',N'غينيا','Guinean',N'غيني');
INSERT INTO countries VALUES ('GW', 'Guinea-Bissau',N'غينيا-بيساو','Guinea-Bissauan',N'غيني');
INSERT INTO countries VALUES ('GY', 'Guyana',N'غيانا','Guyanese',N'غياني');
INSERT INTO countries VALUES ('HT', 'Haiti',N'هايتي','Haitian',N'هايتي');
INSERT INTO countries VALUES ('HM', 'Heard and Mc Donald Islands',N'جزيرة هيرد وجزر ماكدونالد','Heard and Mc Donald Islanders',N'جزيرة هيرد وجزر ماكدونالد');
INSERT INTO countries VALUES ('HN', 'Honduras',N'هندوراس','Honduran',N'هندوراسي');
INSERT INTO countries VALUES ('HK', 'Hong Kong',N'هونغ كونغ','Hongkongese',N'هونغ كونغي');
INSERT INTO countries VALUES ('HU', 'Hungary',N'المجر','Hungarian',N'مجري');
INSERT INTO countries VALUES ('IS', 'Iceland',N'آيسلندا','Icelandic',N'آيسلندي');
INSERT INTO countries VALUES ('IN', 'India',N'الهند','Indian',N'هندي');
INSERT INTO countries VALUES ('IM', 'Isle of Man',N'جزيرة مان','Manx',N'ماني');
INSERT INTO countries VALUES ('ID', 'Indonesia',N'أندونيسيا','Indonesian',N'أندونيسيي');
INSERT INTO countries VALUES ('IR', 'Iran',N'إيران','Iranian',N'إيراني');
INSERT INTO countries VALUES ('IQ', 'Iraq',N'العراق','Iraqi',N'عراقي');
INSERT INTO countries VALUES ('IE', 'Ireland',N'إيرلندا','Irish',N'إيرلندي');
INSERT INTO countries VALUES ('IL', 'Israel',N'إسرائيل','Israeli',N'إسرائيلي');
INSERT INTO countries VALUES ('IT', 'Italy',N'إيطاليا','Italian',N'إيطالي');
INSERT INTO countries VALUES ('CI', 'Ivory Coast',N'ساحل العاج','Ivory Coastian',N'ساحل العاج');
INSERT INTO countries VALUES ('JE', 'Jersey',N'جيرزي','Jersian',N'جيرزي');
INSERT INTO countries VALUES ('JM', 'Jamaica',N'جمايكا','Jamaican',N'جمايكي');
INSERT INTO countries VALUES ('JP', 'Japan',N'اليابان','Japanese',N'ياباني');
INSERT INTO countries VALUES ('JO', 'Jordan',N'الأردن','Jordanian',N'أردني');
INSERT INTO countries VALUES ('KZ', 'Kazakhstan',N'كازاخستان','Kazakh',N'كازاخستاني');
INSERT INTO countries VALUES ('KE', 'Kenya',N'كينيا','Kenyan',N'كيني');
INSERT INTO countries VALUES ('KI', 'Kiribati',N'كيريباتي','I-Kiribati',N'كيريباتي');
INSERT INTO countries VALUES ('KP', 'Korea(North Korea)',N'كوريا الشمالية','North Korean',N'كوري');
INSERT INTO countries VALUES ('KR', 'Korea(South Korea)',N'كوريا الجنوبية','South Korean',N'كوري');
INSERT INTO countries VALUES ('XK', 'Kosovo',N'كوسوفو','Kosovar',N'كوسيفي');
INSERT INTO countries VALUES ('KW', 'Kuwait',N'الكويت','Kuwaiti',N'كويتي');
INSERT INTO countries VALUES ('KG', 'Kyrgyzstan',N'قيرغيزستان','Kyrgyzstani',N'قيرغيزستاني');
INSERT INTO countries VALUES ('LA', 'Lao PDR',N'لاوس','Laotian',N'لاوسي');
INSERT INTO countries VALUES ('LV', 'Latvia',N'لاتفيا','Latvian',N'لاتيفي');
INSERT INTO countries VALUES ('LB', 'Lebanon',N'لبنان','Lebanese',N'لبناني');
INSERT INTO countries VALUES ('LS', 'Lesotho',N'ليسوتو','Basotho',N'ليوسيتي');
INSERT INTO countries VALUES ('LR', 'Liberia',N'ليبيريا','Liberian',N'ليبيري');
INSERT INTO countries VALUES ('LY', 'Libya',N'ليبيا','Libyan',N'ليبي');
INSERT INTO countries VALUES ('LI', 'Liechtenstein',N'ليختنشتين','Liechtenstein',N'ليختنشتيني');
INSERT INTO countries VALUES ('LT', 'Lithuania',N'لتوانيا','Lithuanian',N'لتوانيي');
INSERT INTO countries VALUES ('LU', 'Luxembourg',N'لوكسمبورغ','Luxembourger',N'لوكسمبورغي');
INSERT INTO countries VALUES ('LK', 'Sri Lanka',N'سريلانكا','Sri Lankian',N'سريلانكي');
INSERT INTO countries VALUES ('MO', 'Macau',N'ماكاو','Macanese',N'ماكاوي');
INSERT INTO countries VALUES ('MK', 'Macedonia',N'مقدونيا','Macedonian',N'مقدوني');
INSERT INTO countries VALUES ('MG', 'Madagascar',N'مدغشقر','Malagasy',N'مدغشقري');
INSERT INTO countries VALUES ('MW', 'Malawi',N'مالاوي','Malawian',N'مالاوي');
INSERT INTO countries VALUES ('MY', 'Malaysia',N'ماليزيا','Malaysian',N'ماليزي');
INSERT INTO countries VALUES ('MV', 'Maldives',N'المالديف','Maldivian',N'مالديفي');
INSERT INTO countries VALUES ('ML', 'Mali',N'مالي','Malian',N'مالي');
INSERT INTO countries VALUES ('MT', 'Malta',N'مالطا','Maltese',N'مالطي');
INSERT INTO countries VALUES ('MH', 'Marshall Islands',N'جزر مارشال','Marshallese',N'مارشالي');
INSERT INTO countries VALUES ('MQ', 'Martinique',N'مارتينيك','Martiniquais',N'مارتينيكي');
INSERT INTO countries VALUES ('MR', 'Mauritania',N'موريتانيا','Mauritanian',N'موريتانيي');
INSERT INTO countries VALUES ('MU', 'Mauritius',N'موريشيوس','Mauritian',N'موريشيوسي');
INSERT INTO countries VALUES ('YT', 'Mayotte',N'مايوت','Mahoran',N'مايوتي');
INSERT INTO countries VALUES ('MX', 'Mexico',N'المكسيك','Mexican',N'مكسيكي');
INSERT INTO countries VALUES ('FM', 'Micronesia',N'مايكرونيزيا','Micronesian',N'مايكرونيزيي');
INSERT INTO countries VALUES ('MD', 'Moldova',N'مولدافيا','Moldovan',N'مولديفي');
INSERT INTO countries VALUES ('MC', 'Monaco',N'موناكو','Monacan',N'مونيكي');
INSERT INTO countries VALUES ('MN', 'Mongolia',N'منغوليا','Mongolian',N'منغولي');
INSERT INTO countries VALUES ('ME', 'Montenegro',N'الجبل الأسود','Montenegrin',N'الجبل الأسود');
INSERT INTO countries VALUES ('MS', 'Montserrat',N'مونتسيرات','Montserratian',N'مونتسيراتي');
INSERT INTO countries VALUES ('MA', 'Morocco',N'المغرب','Moroccan',N'مغربي');
INSERT INTO countries VALUES ('MZ', 'Mozambique',N'موزمبيق','Mozambican',N'موزمبيقي');
INSERT INTO countries VALUES ('MM', 'Myanmar',N'ميانمار','Myanmarian',N'ميانماري');
INSERT INTO countries VALUES ('NA', 'Namibia',N'ناميبيا','Namibian',N'ناميبي');
INSERT INTO countries VALUES ('NR', 'Nauru',N'نورو','Nauruan',N'نوري');
INSERT INTO countries VALUES ('NP', 'Nepal',N'نيبال','Nepalese',N'نيبالي');
INSERT INTO countries VALUES ('NL', 'Netherlands',N'هولندا','Dutch',N'هولندي');
INSERT INTO countries VALUES ('AN', 'Netherlands Antilles',N'جزر الأنتيل الهولندي','Dutch Antilier',N'هولندي');
INSERT INTO countries VALUES ('NC', 'New Caledonia',N'كاليدونيا الجديدة','New Caledonian',N'كاليدوني');
INSERT INTO countries VALUES ('NZ', 'New Zealand',N'نيوزيلندا','New Zealander',N'نيوزيلندي');
INSERT INTO countries VALUES ('NI', 'Nicaragua',N'نيكاراجوا','Nicaraguan',N'نيكاراجوي');
INSERT INTO countries VALUES ('NE', 'Niger',N'النيجر','Nigerien',N'نيجيري');
INSERT INTO countries VALUES ('NG', 'Nigeria',N'نيجيريا','Nigerian',N'نيجيري');
INSERT INTO countries VALUES ('NU', 'Niue',N'ني','Niuean',N'ني');
INSERT INTO countries VALUES ('NF', 'Norfolk Island',N'جزيرة نورفولك','Norfolk Islander',N'نورفوليكي');
INSERT INTO countries VALUES ('MP', 'Northern Mariana Islands',N'جزر ماريانا الشمالية','Northern Marianan',N'ماريني');
INSERT INTO countries VALUES ('NO', 'Norway',N'النرويج','Norwegian',N'نرويجي');
INSERT INTO countries VALUES ('OM', 'Oman',N'عمان','Omani',N'عماني');
INSERT INTO countries VALUES ('PK', 'Pakistan',N'باكستان','Pakistani',N'باكستاني');
INSERT INTO countries VALUES ('PW', 'Palau',N'بالاو','Palauan',N'بالاوي');
INSERT INTO countries VALUES ('PS', 'Palestine',N'فلسطين','Palestinian',N'فلسطيني');
INSERT INTO countries VALUES ('PA', 'Panama',N'بنما','Panamanian',N'بنمي');
INSERT INTO countries VALUES ('PG', 'Papua New Guinea',N'بابوا غينيا الجديدة','Papua New Guinean',N'بابوي');
INSERT INTO countries VALUES ('PY', 'Paraguay',N'باراغواي','Paraguayan',N'بارغاوي');
INSERT INTO countries VALUES ('PE', 'Peru',N'بيرو','Peruvian',N'بيري');
INSERT INTO countries VALUES ('PH', 'Philippines',N'الفليبين','Filipino',N'فلبيني');
INSERT INTO countries VALUES ('PN', 'Pitcairn',N'بيتكيرن','Pitcairn Islander',N'بيتكيرني');
INSERT INTO countries VALUES ('PL', 'Poland',N'بولونيا','Polish',N'بوليني');
INSERT INTO countries VALUES ('PT', 'Portugal',N'البرتغال','Portuguese',N'برتغالي');
INSERT INTO countries VALUES ('PR', 'Puerto Rico',N'بورتو ريكو','Puerto Rican',N'بورتي');
INSERT INTO countries VALUES ('QA', 'Qatar',N'قطر','Qatari',N'قطري');
INSERT INTO countries VALUES ('RE', 'Reunion Island',N'ريونيون','Reunionese',N'ريونيوني');
INSERT INTO countries VALUES ('RO', 'Romania',N'رومانيا','Romanian',N'روماني');
INSERT INTO countries VALUES ('RU', 'Russian',N'روسيا','Russian',N'روسي');
INSERT INTO countries VALUES ('RW', 'Rwanda',N'رواندا','Rwandan',N'رواندا');
INSERT INTO countries VALUES ('KN', 'Saint Kitts and Nevis',N'سانت كيتس ونيفس,','Kittitian/Nevisian',N'سانت كيتس ونيفس');
INSERT INTO countries VALUES ('MF', 'Saint Martin (French part)',N'ساينت مارتن فرنسي','St. Martian(French)',N'ساينت مارتني فرنسي');
INSERT INTO countries VALUES ('SX', 'Sint Maarten (Dutch part)',N'ساينت مارتن هولندي','St. Martian(Dutch)',N'ساينت مارتني هولندي');
INSERT INTO countries VALUES ('LC', 'Saint Pierre and Miquelon',N'سان بيير وميكلون','St. Pierre and Miquelon',N'سان بيير وميكلوني');
INSERT INTO countries VALUES ('VC', 'Saint Vincent and the Grenadines',N'سانت فنسنت وجزر غرينادين','Saint Vincent and the Grenadines',N'سانت فنسنت وجزر غرينادين');
INSERT INTO countries VALUES ('WS', 'Samoa',N'ساموا','Samoan',N'ساموي');
INSERT INTO countries VALUES ('SM', 'San Marino',N'سان مارينو','Sammarinese',N'ماريني');
INSERT INTO countries VALUES ('ST', 'Sao Tome and Principe',N'ساو تومي وبرينسيبي','Sao Tomean',N'ساو تومي وبرينسيبي');
INSERT INTO countries VALUES ('SA', 'Saudi Arabia',N'المملكة العربية السعودية','Saudi Arabian',N'سعودي');
INSERT INTO countries VALUES ('SN', 'Senegal',N'السنغال','Senegalese',N'سنغالي');
INSERT INTO countries VALUES ('RS', 'Serbia',N'صربيا','Serbian',N'صربي');
INSERT INTO countries VALUES ('SC', 'Seychelles',N'سيشيل','Seychellois',N'سيشيلي');
INSERT INTO countries VALUES ('SL', 'Sierra Leone',N'سيراليون','Sierra Leonean',N'سيراليوني');
INSERT INTO countries VALUES ('SG', 'Singapore',N'سنغافورة','Singaporean',N'سنغافوري');
INSERT INTO countries VALUES ('SK', 'Slovakia',N'سلوفاكيا','Slovak',N'سولفاكي');
INSERT INTO countries VALUES ('SI', 'Slovenia',N'سلوفينيا','Slovenian',N'سولفيني');
INSERT INTO countries VALUES ('SB', 'Solomon Islands',N'جزر سليمان','Solomon Island',N'جزر سليمان');
INSERT INTO countries VALUES ('SO', 'Somalia',N'الصومال','Somali',N'صومالي');
INSERT INTO countries VALUES ('ZA', 'South Africa',N'جنوب أفريقيا','South African',N'أفريقي');
INSERT INTO countries VALUES ('GS', 'South Georgia and the South Sandwich',N'المنطقة القطبية الجنوبية','South Georgia and the South Sandwich',N'لمنطقة القطبية الجنوبية');
INSERT INTO countries VALUES ('SS', 'South Sudan',N'السودان الجنوبي','South Sudanese',N'سوادني جنوبي');
INSERT INTO countries VALUES ('ES', 'Spain',N'إسبانيا','Spanish',N'إسباني');
INSERT INTO countries VALUES ('SH', 'Saint Helena',N'سانت هيلانة','St. Helenian',N'هيلاني');
INSERT INTO countries VALUES ('SD', 'Sudan',N'السودان','Sudanese',N'سوداني');
INSERT INTO countries VALUES ('SR', 'Suriname',N'سورينام','Surinamese',N'سورينامي');
INSERT INTO countries VALUES ('SJ', 'Svalbard and Jan Mayen',N'سفالبارد ويان ماين','Svalbardian/Jan Mayenian',N'سفالبارد ويان ماين');
INSERT INTO countries VALUES ('SZ', 'Swaziland',N'سوازيلند','Swazi',N'سوازيلندي');
INSERT INTO countries VALUES ('SE', 'Sweden',N'السويد','Swedish',N'سويدي');
INSERT INTO countries VALUES ('CH', 'Switzerland',N'سويسرا','Swiss',N'سويسري');
INSERT INTO countries VALUES ('SY', 'Syria',N'سوريا','Syrian',N'سوري');
INSERT INTO countries VALUES ('TW', 'Taiwan',N'تايوان','Taiwanese',N'تايواني');
INSERT INTO countries VALUES ('TJ', 'Tajikistan',N'طاجيكستان','Tajikistani',N'طاجيكستاني');
INSERT INTO countries VALUES ('TZ', 'Tanzania',N'تنزانيا','Tanzanian',N'تنزانيي');
INSERT INTO countries VALUES ('TH', 'Thailand',N'تايلندا','Thai',N'تايلندي');
INSERT INTO countries VALUES ('TL', 'Timor-Leste',N'تيمور الشرقية','Timor-Lestian',N'تيموري');
INSERT INTO countries VALUES ('TG', 'Togo',N'توغو','Togolese',N'توغي');
INSERT INTO countries VALUES ('TK', 'Tokelau',N'توكيلاو','Tokelaian',N'توكيلاوي');
INSERT INTO countries VALUES ('TO', 'Tonga',N'تونغا','Tongan',N'تونغي');
INSERT INTO countries VALUES ('TT', 'Trinidad and Tobago',N'ترينيداد وتوباغو','Trinidadian/Tobagonian',N'ترينيداد وتوباغو');
INSERT INTO countries VALUES ('TN', 'Tunisia',N'تونس','Tunisian',N'تونسي');
INSERT INTO countries VALUES ('TR', 'Turkey',N'تركيا','Turkish',N'تركي');
INSERT INTO countries VALUES ('TM', 'Turkmenistan',N'تركمانستان','Turkmen',N'تركمانستاني');
INSERT INTO countries VALUES ('TC', 'Turks and Caicos Islands',N'جزر توركس وكايكوس','Turks and Caicos Islands',N'جزر توركس وكايكوس');
INSERT INTO countries VALUES ('TV', 'Tuvalu',N'توفالو','Tuvaluan',N'توفالي');
INSERT INTO countries VALUES ('UG', 'Uganda',N'أوغندا','Ugandan',N'أوغندي');
INSERT INTO countries VALUES ('UA', 'Ukraine',N'أوكرانيا','Ukrainian',N'أوكراني');
INSERT INTO countries VALUES ('AE', 'United Arab Emirates',N'الإمارات العربية المتحدة','Emirati',N'إماراتي');
INSERT INTO countries VALUES ('GB', 'United Kingdom',N'المملكة المتحدة','British',N'بريطاني');
INSERT INTO countries VALUES ('US', 'United States',N'الولايات المتحدة','American',N'أمريكي');
INSERT INTO countries VALUES ('UM', 'US Minor Outlying Islands',N'قائمة الولايات والمناطق الأمريكية','US Minor Outlying Islander',N'أمريكي');
INSERT INTO countries VALUES ('UY', 'Uruguay',N'أورغواي','Uruguayan',N'أورغواي');
INSERT INTO countries VALUES ('UZ', 'Uzbekistan',N'أوزباكستان','Uzbek',N'أوزباكستاني');
INSERT INTO countries VALUES ('VU', 'Vanuatu',N'فانواتو','Vanuatuan',N'فانواتي');
INSERT INTO countries VALUES ('VE', 'Venezuela',N'فنزويلا','Venezuelan',N'فنزويلي');
INSERT INTO countries VALUES ('VN', 'Vietnam',N'فيتنام','Vietnamese',N'فيتنامي');
INSERT INTO countries VALUES ('VI', 'Virgin Islands (U.S.)',N'الجزر العذراء الأمريكي','American Virgin Islander',N'أمريكي');
INSERT INTO countries VALUES ('VA', 'Vatican City',N'فنزويلا','Vatican',N'فاتيكاني');
INSERT INTO countries VALUES ('WF', 'Wallis and Futuna Islands',N'والس وفوتونا','Wallisian/Futunan',N'فوتوني');
INSERT INTO countries VALUES ('EH', 'Western Sahara',N'الصحراء الغربية','Sahrawian',N'صحراوي');
INSERT INTO countries VALUES ('YE', 'Yemen',N'اليمن','Yemeni',N'يمني');
INSERT INTO countries VALUES ('ZM', 'Zambia',N'زامبيا','Zambian',N'زامبياني');
INSERT INTO countries VALUES ('ZW', 'Zimbabwe',N'زمبابوي','Zimbabwean',N'زمبابوي');